### ISSUE TITLE
Что дальше?

### ISSUE THREAD

**Issue by Atorich** [glibin/tortik#17]
Какова дальнейшая судьба тортика? В целом достаточно вкусно было рассказано на пайконе, но вот то, что проект, в отличие от фронтика, и не обновлялся с тех пор, немного озадачивает. Прольете свет, если не сложно? :)

**Comment by Splurov** [comment]
Решили, что лучше хорошие идеи из тортика перенести во фронтик, так и сделали.

**Comment by glibin** [comment]
Небольшими темпами я развиваю его в отдельном форке: https://github.com/glibin/tortik 
В течение одной-двух недель я его залью в стабильный pypi

**Comment by Atorich** [comment]
Хм. Два ответа немного противоречивых.
На фронтике получилось использовать апстрим торнадо? Я полазил, в зависимостях вроде не он и, опять же, патченный от hh

**Comment by Splurov** [comment]
> На фронтике получилось использовать апстрим торнадо?

Нет, к сожалению.
Без нескольких патчей никак пока: https://github.com/hhru/tornado/compare/tornadoweb:master...master

**Comment by Atorich** [comment]
Я, если честно, во фронтик особо не вникал, но с конференции помню, про него Виталий говорил, что нельзя просто так взять и сразу его использовать. Какие подводные камни помимо патча торнадо там имеются?

**Comment by SuminAndrew** [comment]
С апстримом тоже должен заводиться, и некоторые наши патчи мы постепенно вливаем в него.

**Comment by SuminAndrew** [comment]
Подводные камни — придётся разобраться, что к чему, потому что приложения на фронтике от торнадовских немного отличаются. Основные моменты описаны в документации в гитхабе.
